services:
  website:
    image: nginx:alpine
    container_name: fsm-nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /keys/certificate.key:/etc/nginx/tls/certificate.key:ro
      - /keys/certificate.crt:/etc/nginx/tls/certificate.crt:ro
      - ./cronfile:/etc/cron.d/cronfile:ro
      - ./script.sh:/script.sh:ro
      - ./src/html/app.js:/usr/share/nginx/html/app.js
      - ./src/html/style.css:/usr/share/nginx/html/style.css
    environment:
      - CRON_TZ=UTC
    command: sh -c "cat /etc/cron.d/cronfile >> /var/spool/cron/crontabs/root && crond && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
    restart: always
